CI: azure
boost: 1.74.0
boost_cpp: 1.74.0
c_compiler: vs2017
cairo: '1.16'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
curl: '7'
cxx_compiler: vs2017
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fontconfig: '2.13'
fortran_compiler: gfortran
freetype: '2'
glib: '2'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libcurl: '7'
libiconv: '1.16'
libpng: '1.6'
libtiff: '4'
lua: '5'
numpy: '1.16'
openjpeg: '2.4'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  cairo:
    max_pin: x.x
  curl:
    max_pin: x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  jpeg:
    max_pin: x
  libcurl:
    max_pin: x
  libiconv:
    max_pin: x.x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
  openjpeg:
    max_pin: x.x
  qt:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.9'
qt: '5.12'
r_base: '3.4'
target_platform: win-64
vc: '14'
zlib: '1.2'
