# This file created by conda-build 3.21.6
# ------------------------------------------------

package:
  name: poppler
  version: 21.11.0
source:
  patches:
    - disable-libtiff-win32-io.patch
    - exportsymbols.patch
    - glib-mkenums-wrapped.win.patch
    - windows-data.patch
  sha256: 31b76b5cac0a48612fdd154c02d9eca01fd38fb8eaa77c1196840ecdeb53a584
  url: https://poppler.freedesktop.org/poppler-21.11.0.tar.xz
build:
  detect_binary_files_with_prefix: true
  noarch: false
  noarch_python: false
  number: '0'
  script: install.bat
  string: h24fffdf_0
requirements:
  build:
    - cmake 3.21.3 h39d44d4_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - m2w64-pkg-config 0.29.1 2
    - make 4.3 h3d2af85_1
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 h2d74725_1
    - perl 5.32.1.1 1_h57928b3_strawberry
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - vs2015_runtime 14.29.30037 h902a5da_5
    - vs2017_win-64 19.16.27038 h2e3bad8_2
    - vswhere 2.8.4 h57928b3_0
  host:
    - boost-cpp 1.74.0 h5b4e17d_5
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2021.10.8 h5b45459_0
    - cairo 1.16.0 h15b3021_1009
    - curl 7.79.1 h789b8ee_1
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 hab24e00_0
    - fontconfig 2.13.1 h1989441_1005
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.10.4 h546665d_1
    - gettext 0.19.8.1 ha2e2712_1008
    - glib 2.70.0 h7755175_1
    - glib-tools 2.70.0 h7755175_1
    - icu 69.1 h0e60522_0
    - jbig 2.1 h8d14728_2003
    - jpeg 9d h8ffe710_0
    - krb5 1.19.2 h6da9e4a_3
    - lcms2 2.12 h2a16943_0
    - lerc 3.0 h0e60522_0
    - libcurl 7.79.1 h789b8ee_1
    - libdeflate 1.8 h8ffe710_0
    - libffi 3.4.2 h0e60522_4
    - libglib 2.70.0 h3be07f2_1
    - libiconv 1.16 he774522_0
    - libpng 1.6.37 h1d00b33_2
    - libssh2 1.10.0 h9a1e1f7_2
    - libtiff 4.3.0 hd413186_2
    - libxml2 2.9.12 hf5bbc77_1
    - libzlib 1.2.11 h8ffe710_1013
    - lz4-c 1.9.3 h8ffe710_1
    - openjpeg 2.4.0 hb211442_1
    - openssl 3.0.0 h8ffe710_2
    - pcre 8.45 h0e60522_0
    - pixman 0.40.0 h8ffe710_0
    - python 3.10.0 hcf16a7b_2_cpython
    - sqlite 3.36.0 h8ffe710_2
    - tk 8.6.11 h8ffe710_1
    - tzdata 2021e he74cb21_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - vs2015_runtime 14.29.30037 h902a5da_5
    - xz 5.2.5 h62dcd97_1
    - zlib 1.2.11 h8ffe710_1013
    - zstd 1.5.0 h6255e5f_0
  run:
    - boost-cpp >=1.74.0,<1.74.1.0a0
    - cairo >=1.16.0,<1.17.0a0
    - fontconfig >=2.13.1,<3.0a0
    - fonts-conda-ecosystem
    - freetype >=2.10.4,<3.0a0
    - gettext >=0.19.8.1,<1.0a0
    - jpeg >=9d,<10a
    - lcms2 >=2.12,<3.0a0
    - libcurl >=7.79.1,<8.0a0
    - libglib >=2.70.0,<3.0a0
    - libiconv >=1.16,<1.17.0a0
    - libpng >=1.6.37,<1.7.0a0
    - libtiff >=4.3.0,<5.0a0
    - libzlib >=1.2.11,<1.3.0a0
    - openjpeg >=2.4.0,<2.5.0a0
    - poppler-data
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012
test:
  commands:
    - pdfinfo -listenc
    - pdfunite --help
    - pdftocairo --help
about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The Poppler PDF manipulation library.
extra:
  copy_test_source_files: true
  feedstock-name: poppler
  final: true
  recipe-maintainers:
    - ocefpaf
    - pkgw
    - xhochy
